apiVersion: app.k8s.io/v1beta1
kind: Application
  name: tethys
  namespace: tethys-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - tethys
