apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: tethys
  name: tethys-placement-frontend
  namespace: tethys-app
spec:
  clusterSelector:
    matchLabels:
      environment: front
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: tethys
  name: tethys-placement-backend
  namespace: tethys-app
spec:
  clusterSelector:
    matchLabels:
      environment: back
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: tethys
  name: tethys-placement-dmz
  namespace: tethys-app
spec:
  clusterSelector:
    matchLabels:
      environment: dmz
