apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: gogs
  name: gogs-placement-frontend
  namespace: gogs-multicluster
spec:
  clusterSelector:
    matchLabels:
      environment: front
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: gogs
  name: gogs-placement-backend
  namespace: gogs-multicluster
spec:
  clusterSelector:
    matchLabels:
      environment: back
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: gogs
  name: gogs-placement-dmz
  namespace: gogs-multicluster
spec:
  clusterSelector:
    matchLabels:
      environment: dmz
