apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
  labels:
    app: gogs
  name: gogs-subscription-front-0
spec:
  channel: demo-gogs-multicluster/chartmuseum-local
  name: gogs-helm-umbrella
  packageOverrides:
  - packageName: gogs-helm-umbrella
    packageAlias: gogs
    packageOverrides:
    - path: spec
      value:
        image:
          pullPolicy: IfNotPresent
          # Overrides the image tag whose default is the chart appVersion.
          tag: ""


        gogs:
          enabled: true
          hostname: demo-gogs-multicluster.apps.ocp4-front.openshift-v4.dcpro31.opk.recouv

        postgresql:
          enabled: false

        tags:
          front-end: true
          back-end: false

        global:
          postgresql:
            hostname: 192.168.1.150
            port: 5432
            postgresqlUsername: gogs
            postgresqlPassword: gogslebponge616

  placement:
    placementRef:
      kind: PlacementRule
      name: gogs-placement-frontend
